# Generated by Django 6.0.4 on 2026-04-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
