# Generated by Django 6.0.4 on 2026-04-21 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_invitation_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='medredaktorer',
            field=models.ManyToManyField(blank=True, help_text='Andre brugere der må se og redigere dette event.', related_name='redaktor_for_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='oprettet_af',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mine_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='sidste_svardag',
            field=models.DateTimeField(blank=True, help_text='Efter denne dato kan gæster kun ændre svar fra "ja" til "nej" (med årsag).', null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='afbud_aarsag',
            field=models.TextField(blank=True, help_text='Udfyldes hvis gæsten melder afbud efter svarfristen.'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='svar_opdateret',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
