# Generated by Django 6.0.4 on 2026-04-30 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_medredaktorer_event_oprettet_af_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Husstand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(help_text='Fx "Familien Hansen"', max_length=200)),
                ('token', models.SlugField(blank=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Afventer'), ('maaske', 'Måske (hele husstanden)'), ('individuelt', 'Svar afgivet individuelt'), ('nej', 'Hele husstanden kommer ikke')], default='pending', max_length=15)),
                ('afbud_aarsag', models.TextField(blank=True, help_text='Udfyldes hvis husstanden melder afbud efter svarfristen.')),
                ('svar_opdateret', models.DateTimeField(blank=True, null=True)),
                ('oprettet', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='husstande', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='HusstandEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('send_invitation', models.BooleanField(default=True, help_text='Skal invitationsmails sendes til denne adresse?')),
                ('husstand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='events.husstand')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Husstandsmedlem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Afventer'), ('ja', 'Deltager'), ('nej', 'Deltager ikke')], default='pending', max_length=10)),
                ('husstand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medlemmer', to='events.husstand')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
