# Generated by Django 6.0.4 on 2026-05-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_husstand_husstandemail_husstandsmedlem'),
    ]

    operations = [
        migrations.AddField(
            model_name='husstandsmedlem',
            name='email',
            field=models.EmailField(blank=True, help_text='Email til dette medlem (valgfrit).', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='husstandsmedlem',
            name='send_invitation',
            field=models.BooleanField(default=True, help_text='Skal invitation sendes til denne email?'),
        ),
    ]
