# Generated by Django 6.0.4 on 2026-05-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_husstandsmedlem_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sidste_svardag',
            field=models.DateTimeField(blank=True, help_text='Efter denne dato kan gæster kun ændre svar fra "ja" til "nej"', null=True),
        ),
        migrations.DeleteModel(
            name='HusstandEmail',
        ),
    ]
