# Generated by Django 6.0.4 on 2026-05-05 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_sidste_svardag_delete_husstandemail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('noter', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, help_text='Kommaseparerede tags, fx "familie, venner"', max_length=255)),
                ('oprettet', models.DateTimeField(auto_now_add=True)),
                ('sidst_opdateret', models.DateTimeField(auto_now=True)),
                ('shared_with', models.ManyToManyField(blank=True, related_name='delte_kontakter', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kontakter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['navn'],
                'constraints': [models.UniqueConstraint(fields=('user', 'email'), name='unique_contact_per_user')],
            },
        ),
    ]
