# Generated by Django 6.0.4 on 2026-05-05 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GaestebogHusstand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(help_text='Fx "Familien Hansen"', max_length=200)),
                ('oprettet', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaestebog_husstande', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['navn'],
            },
        ),
        migrations.CreateModel(
            name='GaestebogMedlem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('husstand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medlemmer', to='events.gaesteboghusstand')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
