# Generated by Django 6.0.4 on 2026-05-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_gaesteboghusstand_tags_shared_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='baggrundsbillede',
            field=models.ImageField(blank=True, help_text='Vises i headeren på RSVP-siden (anbefalet: 1200×400 px).', null=True, upload_to='event_baggrunde/', verbose_name='Baggrundsbillede'),
        ),
        migrations.AddField(
            model_name='event',
            name='oenskeliste_url',
            field=models.URLField(blank=True, help_text='Link til ønskeliste (fx Ønskeskyen.dk). Vises på RSVP-siden.', verbose_name='Ønskeliste-link'),
        ),
        migrations.AddField(
            model_name='event',
            name='tema',
            field=models.CharField(choices=[('standard', 'Standard'), ('foedselsdag', 'Fødselsdag'), ('fest', 'Fest / Nytår'), ('barnedag', 'Barnedåb'), ('bryllup', 'Bryllup'), ('jul', 'Jul'), ('paaske', 'Påske'), ('sommer', 'Sommerfest')], default='standard', max_length=20, verbose_name='Tema'),
        ),
    ]
