# Generated by Django 6.0.4 on 2026-05-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_personalisering'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='farve_baggrund',
            field=models.CharField(blank=True, default='#ffffff', help_text='Sidens baggrundsfarve (standard: hvid).', max_length=7, verbose_name='Baggrundsfarve'),
        ),
        migrations.AddField(
            model_name='event',
            name='farve_moenster',
            field=models.CharField(blank=True, default='', help_text='Farve på illustrationerne i baggrunden. Tom = brug tema-farve.', max_length=7, verbose_name='Mønsterfarve'),
        ),
    ]
