# Generated by Django 6.0.4 on 2026-05-06 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_farver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delelink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.SlugField(blank=True, max_length=12, unique=True)),
                ('type', models.CharField(choices=[('solo', 'Solo'), ('husstand', 'Husstand')], max_length=10)),
                ('oprettet', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delelinks', to='events.event')),
            ],
            options={
                'unique_together': {('event', 'type')},
            },
        ),
    ]
