# Generated by Django 6.0.5 on 2026-05-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_delelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reminder_dage_foer',
            field=models.PositiveIntegerField(blank=True, help_text='Antal dage før eventet den første reminder-mail sendes til "måske"-gæster.', null=True, verbose_name='Send første reminder'),
        ),
        migrations.AddField(
            model_name='event',
            name='reminder_interval',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'Ingen yderligere reminders'), (1, 'Hver dag'), (2, 'Hver 2. dag'), (3, 'Hver 3. dag'), (7, 'Ugentlig')], help_text='Hvor ofte skal der sendes yderligere reminders efter den første?', null=True, verbose_name='Efterfølgende reminders'),
        ),
        migrations.AddField(
            model_name='husstand',
            name='reminder_sendt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='reminder_sendt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
