# Generated by Django 6.0.4 on 2026-05-06 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_reminder_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='afstemning_aktiveret',
            field=models.BooleanField(default=True, help_text='Gæster kan stemme på afstemninger på RSVP-siden.', verbose_name='Afstemning aktiveret'),
        ),
        migrations.AddField(
            model_name='event',
            name='kommentarer_aktiveret',
            field=models.BooleanField(default=True, help_text='Gæster kan skrive kommentarer på RSVP-siden.', verbose_name='Kommentarspor aktiveret'),
        ),
        migrations.CreateModel(
            name='Afstemning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spoergsmaal', models.CharField(max_length=300, verbose_name='Spørgsmål')),
                ('oprettet', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afstemninger', to='events.event')),
            ],
            options={
                'ordering': ['oprettet'],
            },
        ),
        migrations.CreateModel(
            name='AfstemningValg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', models.CharField(max_length=200)),
                ('afstemning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valg', to='events.afstemning')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Kommentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50)),
                ('navn', models.CharField(max_length=100)),
                ('tekst', models.TextField(max_length=1000)),
                ('oprettet', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kommentarer', to='events.event')),
            ],
            options={
                'ordering': ['oprettet'],
            },
        ),
        migrations.CreateModel(
            name='AfstemningsSvar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50)),
                ('navn', models.CharField(max_length=100)),
                ('afstemning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='svar', to='events.afstemning')),
                ('valg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='svar', to='events.afstemningvalg')),
            ],
            options={
                'unique_together': {('afstemning', 'token')},
            },
        ),
    ]
