# Generated by Django 6.0.4 on 2026-05-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_kommentarer_og_afstemning'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='aflysning_besked',
            field=models.TextField(blank=True, help_text='Vises i aflysningsmailen og på RSVP-siden.', verbose_name='Besked til gæsterne'),
        ),
        migrations.AddField(
            model_name='event',
            name='aflyst',
            field=models.BooleanField(default=False, verbose_name='Aflyst'),
        ),
        migrations.AddField(
            model_name='event',
            name='arkiveret',
            field=models.BooleanField(default=False, verbose_name='Arkiveret'),
        ),
    ]
