# Generated by Django 6.0.4 on 2026-05-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='vis_deltagerliste',
            field=models.BooleanField(default=True, help_text='Gæster kan se hvem der ellers har sagt ja.', verbose_name='Vis deltagerliste for gæster'),
        ),
    ]
