"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-=_qs0yuanxed%=ga2!7q9r!-fx$hx&%%t&1vrgu%73v78jv)*u')

DEBUG = os.getenv('DEBUG', 'True') == 'True'

ADMIN_URL = os.getenv('ADMIN_URL', 'admin/')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', 'http://localhost').split(',')

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'events',
    'django_q',
    'axes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Django-Axes (login brute-force protection)
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1           # hours before locked IP can try again
AXES_RESET_ON_SUCCESS = True
AXES_LOCKOUT_PARAMETERS = ['ip_address']

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

if os.getenv('DB_ENGINE') == 'postgresql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'vibe_invite'),
            'USER': os.getenv('DB_USER', 'vibe_invite'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'vibe_invite_db'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'da'
TIME_ZONE = 'Europe/Copenhagen'
USE_I18N = True
USE_TZ = True

LANGUAGES = [
    ('da', 'Dansk'),
    ('en', 'English'),
]

LOCALE_PATHS = [BASE_DIR / 'locale']

STATICFILES_DIRS = [BASE_DIR / 'events' / 'static']
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Cloud media storage (S3 / Cloudflare R2 / compatible)
# Set USE_S3=True in .env to activate. Leave unset for local file storage.
_USE_S3 = os.getenv('USE_S3', 'False') == 'True'

if _USE_S3:
    # Credentials
    AWS_ACCESS_KEY_ID     = os.getenv('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
    # Optional: custom endpoint for Cloudflare R2, MinIO, etc.
    # Leave unset for standard AWS S3.
    _endpoint = os.getenv('AWS_S3_ENDPOINT_URL')
    if _endpoint:
        AWS_S3_ENDPOINT_URL = _endpoint
    # Region — required for AWS S3, optional for R2
    _region = os.getenv('AWS_S3_REGION_NAME')
    if _region:
        AWS_S3_REGION_NAME = _region
    # Public URL prefix (optional — set if using a custom domain / CDN)
    _custom_domain = os.getenv('AWS_S3_CUSTOM_DOMAIN')
    if _custom_domain:
        AWS_S3_CUSTOM_DOMAIN = _custom_domain
    # Don't cache credentials in boto3 (useful in containers)
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = os.getenv('AWS_DEFAULT_ACL', 'private')
    AWS_QUERYSTRING_AUTH = os.getenv('AWS_QUERYSTRING_AUTH', 'True') == 'True'
    # Use S3 for media files
    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
            'OPTIONS': {
                'location': os.getenv('AWS_MEDIA_LOCATION', 'media'),
            },
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }
    MEDIA_URL = (
        f"https://{AWS_S3_CUSTOM_DOMAIN}/{os.getenv('AWS_MEDIA_LOCATION', 'media')}/"
        if _custom_domain
        else f"https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/{os.getenv('AWS_MEDIA_LOCATION', 'media')}/"
    )
    MEDIA_ROOT = ''  # not used when S3 is active
else:
    MEDIA_ROOT = BASE_DIR / 'media'
    MEDIA_URL = '/media/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Auth
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# Email
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.example.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@example.com')
SITE_URL = os.getenv('SITE_URL', 'http://localhost:8000')
ADMINS = [('Admin', os.getenv('ADMIN_EMAIL', 'admin@example.com'))]

# Sikkerhed — altid aktive
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30  # 30 dage

# Sikkerhed — aktiveres kun i produktion (DEBUG=False)
if not DEBUG:
    if 'insecure' in SECRET_KEY:
        raise RuntimeError(
            "SECRET_KEY indeholder 'insecure' og er ikke egnet til produktion. "
            "Sæt en stærk tilfældig SECRET_KEY i .env."
        )
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000          # 1 år
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Stol på X-Forwarded-Proto fra reverse proxy (Traefik, Caddy, NPM, Pangolin, Nginx)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Django-Q2
Q_CLUSTER = {
    'name': 'vibe_invite',
    'orm': 'default',
    'workers': 2,
    'timeout': 90,
    'retry': 120,
    'poll': 5,
    'max_attempts': 3,
}

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO' if DEBUG else 'WARNING',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'events': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

if not DEBUG:
    LOGGING['handlers']['file'] = {
        'class': 'logging.handlers.RotatingFileHandler',
        'filename': BASE_DIR / 'logs' / 'django.log',
        'maxBytes': 1024 * 1024 * 5,  # 5 MB
        'backupCount': 3,
        'formatter': 'verbose',
    }
    for logger_name in ('root', 'django', 'django.security', 'events'):
        target = LOGGING['root'] if logger_name == 'root' else LOGGING['loggers'][logger_name]
        target['handlers'].append('file')